/**
 * 
 */
package com.venafi.vcert.sdk.example.ssh;

import com.venafi.vcert.sdk.Config;
import com.venafi.vcert.sdk.VCertTknClient;
import com.venafi.vcert.sdk.certificate.SshCertRetrieveDetails;
import com.venafi.vcert.sdk.certificate.SshCertificateRequest;
import com.venafi.vcert.sdk.endpoint.Authentication;
import com.venafi.vcert.sdk.endpoint.ConnectorType;

/**
 * /**
 * The following test is to show how to use the SSH Certificate feature
 * in order to create and retrieve a SSH Certificate from TPP.
 * @author Marcos E. Albornoz Abud
 *
 */
public class SshCertificateRequestRetrieveWithOutKeyPairProvided {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
        try {
        	String keyId = "<KEY_ID>";
            String cadn = "<TPP_SSH_CA>";
            String user = "<TPPUSER>";
            String password = "<TPPPASSWORD>";
            String baseUri = "<TPP_URL>";
    		
            //1. Get a VCertClient for TPP setting the scope to "ssh:manage"
            Authentication auth = Authentication.builder()
                    .user(user)
                    .password(password)
                    .scope("ssh:manage")
                    .build();


            Config config = Config.builder()
                    .connectorType(ConnectorType.TPP_TOKEN)
                    .baseUrl(baseUri)
                    .build();

            VCertTknClient client = new VCertTknClient(config);
            client.getAccessToken(auth);
            
            //2. Get an instance of com.venafi.vcert.sdk.certificate.SshCertificateRequest class.
            //That can be done using the builder provided by the PolicySpecification
    		SshCertificateRequest req = new SshCertificateRequest()
    				.keyId(keyId)
    				.validityPeriod("4h")// if you omit it, then the validity period of the CIT will be used
    				.cadn(cadn);

            //3. Use the VCertClient method requestSshCertificate() to request the creation of a new 
            // SSH Certificate on TPP. This will return the DN of the created SSH Certificate which 
            // will be used to retrieve the created SSH Certificate.
    		String pickUpID = client.requestSshCertificate(req);
    		
    		//4. Set the pickUp ID to the SshCertificateRequest created. You can create a new one
    		// but in order to avoid the boilerplate, it's preferable to use the already one created.
    		req.pickupID(pickUpID);
    		
    		//4a. you can set a passphrase for the Private Key of the KeyPair that will be generated by TPP.
    		req.privateKeyPassphrase("my-passphrase");

            //5. Use the VCertClient method retrieveSshCertificate() to retrieve the created
    		// SSH Certificate on TPP. It will return an instance of SshCertRetrieveDetails which 
    		// will contain the Ssh Certificate Data, the Public and Private Keys, etc.
    		SshCertRetrieveDetails sshCertRetrieveDetails  = client.retrieveSshCertificate(req);
    		
            client.revokeAccessToken();

        } catch ( Exception e) {
            e.printStackTrace();
        }
    }

}
